#!/bin/bash

NAME=fastapi-app
DIR=/workspace/workspace_aida_fastapi/trinity_fastapi
USER=alabadmin
GROUP=alabadmin
WORKERS=128
WORKER_CLASS=uvicorn.workers.UvicornWorker
VENV=$DIR/.venv/bin/activate
BIND=unix:$DIR/run/gunicorn.sock
LOG_LEVEL=error

cd $DIR
conda activate Trinity3

exec gunicorn main:app \
  --name $NAME \
  --workers $WORKERS \
  --worker-class $WORKER_CLASS \
  --user=$USER \
  --group=$GROUP \
  --bind=$BIND \
  --log-level=$LOG_LEVEL \
  --log-file=-